# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'siparisiptal.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(729, 444)
        self.tablo = QtWidgets.QTableWidget(Form)
        self.tablo.setGeometry(QtCore.QRect(0, 0, 731, 381))
        self.tablo.setObjectName("tablo")
        self.tablo.setColumnCount(6)
        self.tablo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(5, item)
        self.iptalButon = QtWidgets.QPushButton(Form)
        self.iptalButon.setGeometry(QtCore.QRect(290, 390, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.iptalButon.setFont(font)
        self.iptalButon.setObjectName("iptalButon")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Siparis İptal"))
        item = self.tablo.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Sipariş Kodu"))
        item = self.tablo.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Stok Kodu"))
        item = self.tablo.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Ürün"))
        item = self.tablo.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Miktar"))
        item = self.tablo.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Tarih"))
        item = self.tablo.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Fiyat"))
        self.iptalButon.setText(_translate("Form", "İptal"))
