# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sil.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(275, 248)
        self.stokBox = QtWidgets.QComboBox(Form)
        self.stokBox.setGeometry(QtCore.QRect(20, 100, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.stokBox.setFont(font)
        self.stokBox.setObjectName("stokBox")
        self.silButon = QtWidgets.QPushButton(Form)
        self.silButon.setGeometry(QtCore.QRect(100, 180, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.silButon.setFont(font)
        self.silButon.setObjectName("silButon")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(110, 10, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Stok Sil"))
        self.silButon.setText(_translate("Form", "Sil"))
        self.label.setText(_translate("Form", "Stok:"))
